Project 1 [To Do List App]
anishaswain/Simple-JS-Projects pull request #42
Opened 2023-10-04 07:06 UTC by siddhant2002

## **Add the working demo (screen recording) below _(Required)_**

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added issue number to the PR.
- [ ] I have added screen recording of the working app.

2023-10-04 07:26 UTC, siddhant2002 commented
Issue number #1

2023-10-04 11:30 UTC, anishaswain requested changes

2023-10-04 11:30 UTC, anishaswain commented on project1[To_Do_List]/alpha.js
Please add another folder with you github username inside project1 folder and move your js/html/css files inside it (Please go through the redme file carefully)
- squash the commits into one commit and add meaningful commit messge

2023-10-04 15:17 UTC, siddhant2002 commented
Please check the pr

2023-10-04 16:29 UTC, anishaswain requested changes
@siddhant2002 nice work. Please squash the commits into one commit and add meaningful commit message ([How to squash multiple commit messages](https://www.freecodecamp.org/news/git-squash-commits/))

2023-10-05 05:52 UTC, siddhant2002 commented
Please check the pr

2023-10-05 05:53 UTC, anishaswain commented
> Require a

@siddhant2002 there are 17 commits on your PR now. After squash there should only be 1 commit

2023-10-05 07:39 UTC, siddhant2002 commented
@anishaswain Can I raise another pr with 1 commit. It has taken all pull requests to be commits.

2023-10-05 15:52 UTC, anishaswain commented
> @anishaswain Can I raise another pr with 1 commit. It has taken all pull requests as commits.

Sure

2023-10-05 16:00 UTC, closed without merging